# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

def fib(limit):
  if limit <= 1:
    return limit
  else:
    return fib(limit-1) + fib(limit-2)

# Driver Code
limit = 34
sequence = [fib(i) for i in range(limit)]
evens = [x for x in sequence if x % 2 == 0]

print(sequence)
print(sum(evens))
